spring:
  application:
    name: havis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/havisdb
    username: havis
    password: havis
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    show-sql: true
    database: mysql
logging:
  level:
    root: info